# Generated by Django 4.2.2 on 2023-08-14 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mymessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('comment', models.TextField()),
                ('pname', models.CharField(max_length=225)),
                ('plocation', models.CharField(max_length=225)),
                ('msg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
